// ─── TRANSLATION STRINGS ────────────────────────────────────────
const S = {
  // NAV
  'nav.schedule':   { uk:'Записи',      en:'Schedule'   },
  'nav.bookings':   { uk:'Черга',        en:'Queue'      },
  'nav.queue':      { uk:'Черга',       en:'Queue'      },
  'nav.students':   { uk:'Клієнти',        en:'Clients'   },
  'nav.services':   { uk:'Послуги',     en:'Services'   },
  'nav.chats':      { uk:'Чати',        en:'Chats'      },
  'nav.templates':  { uk:'Шаблони',     en:'Templates'  },
  'nav.stats':      { uk:'Статист.',    en:'Stats'      },
  'nav.settings':   { uk:'Налашт.',     en:'Settings'   },
  'nav.journal':    { uk:'Журнал',      en:'Journal'    },

  // COMMON
  'all':            { uk:'Всі',         en:'All'        },
  'save':           { uk:'Зберегти',    en:'Save'       },
  'cancel':         { uk:'Скасувати',   en:'Cancel'     },
  'delete':         { uk:'Видалити',    en:'Delete'     },
  'add':            { uk:'Додати',      en:'Add'        },
  'edit':           { uk:'Редагувати',  en:'Edit'       },
  'search':         { uk:'Пошук…',      en:'Search…'    },
  'loading':        { uk:'Завантаження…', en:'Loading…' },
  'none_found':     { uk:'Нічого не знайдено', en:'Nothing found' },
  'close':          { uk:'Закрити',     en:'Close'      },
  'call':           { uk:'Дзвонити',    en:'Call'       },
  'chat':           { uk:'Чат',         en:'Chat'       },
  'record':         { uk:'Запис',       en:'Booking'    },
  'block':          { uk:'Заблок.',     en:'Block'      },
  'unblock':        { uk:'Розблок.',    en:'Unblock'    },
  'blocked':        { uk:'Заблоковано', en:'Blocked'    },
  'copy':           { uk:'Копіювати',   en:'Copy'       },
  'on':             { uk:'Увімкнено',   en:'On'         },
  'off':            { uk:'Вимкнено',    en:'Off'        },
  'apply':          { uk:'Застосувати', en:'Apply'      },
  'send':           { uk:'Надіслати',   en:'Send'       },
  'active':         { uk:'Активних',    en:'Active'     },
  'archived':       { uk:'Архів',       en:'Archive'    },
  'school':         { uk:'Стандарт',   en:'Standard' },
  'private':        { uk:'Індивідуальний',   en:'Individual'    },
  'hr':             { uk:'год',         en:'hr'         },
  'min':            { uk:'хв',          en:'min'        },
  'uah':            { uk:'₴',           en:'₴'          },
  'days':           { uk:'дн',          en:'days'       },
  'notes':          { uk:'Нотатки',     en:'Notes'      },
  'noshow':         { uk:'No-show',     en:'No-show'    },
  'lessons':        { uk:'Записів',      en:'Lessons'    },
  'income':         { uk:'Дохід',       en:'Income'     },
  'rating':         { uk:'Рейтинг',     en:'Rating'     },
  'last_lesson':    { uk:'Ост. запис',   en:'Last lesson'},
  'total_hours':    { uk:'Годин',       en:'Hours'      },

  // STUDENTS
  'st.search_ph':   { uk:'Ім\'я або телефон…', en:'Name or phone…' },
  'st.count':       { uk:'клієнтів',       en:'clients'   },
  'st.phone':       { uk:'Телефон',     en:'Phone'      },
  'st.discount':    { uk:'Знижка',      en:'Discount'   },
  'st.progress':    { uk:'Прогрес пакета', en:'Package progress' },
  'st.history':     { uk:'Історія записів', en:'Booking history' },
  'st.viber':       { uk:'Вайбер',      en:'Viber'      },
  'st.telegram':    { uk:'Телеграм',    en:'Telegram'   },
  'st.whatsapp':    { uk:'WhatsApp',    en:'WhatsApp'   },

  // BOOKINGS
  'bk.status.pending':   { uk:'Очікує',      en:'Pending'    },
  'bk.status.confirmed': { uk:'Підтверджено', en:'Confirmed'  },
  'bk.status.cancelled': { uk:'Скасовано',   en:'Cancelled'  },
  'bk.status.noshow':    { uk:'Не прийшов',  en:'No-show'    },
  'bk.confirm':     { uk:'Підтвердити',  en:'Confirm'    },
  'bk.cancel':      { uk:'Скасувати',   en:'Cancel'     },
  'bk.noshow':      { uk:'Не прийшов',  en:'No-show'    },
  'bk.today':       { uk:'Сьогодні',    en:'Today'      },
  'bk.tomorrow':    { uk:'Завтра',      en:'Tomorrow'   },
  'bk.week':        { uk:'Тиждень',     en:'Week'       },
  'bk.month':       { uk:'Місяць',      en:'Month'      },
  'bk.sort.date_asc':    { uk:'Дата ↑',      en:'Date ↑'     },
  'bk.sort.date_desc':   { uk:'Дата ↓',      en:'Date ↓'     },
  'bk.sort.name':        { uk:'Ім\'я А-Я',   en:'Name A-Z'   },
  'bk.sort.price':       { uk:'Сума ↓',      en:'Price ↓'    },
  'bk.group.date':       { uk:'По даті',     en:'By date'    },
  'bk.group.status':     { uk:'По статусу',  en:'By status'  },
  'bk.group.type':       { uk:'По типу',     en:'By type'    },
  'bk.pending_count':    { uk:'очікують',    en:'pending'    },
  'bk.total':            { uk:'Всього',      en:'Total'      },

  // CHATS
  'ch.chats':       { uk:'Чати',        en:'Chats'      },
  'ch.search_ph':   { uk:'Пошук контакту…', en:'Search contact…' },
  'ch.online':      { uk:'онлайн',      en:'online'     },
  'ch.offline':     { uk:'офлайн',      en:'offline'    },
  'ch.msg_ph':      { uk:'Повідомлення…', en:'Message…' },
  'ch.quick':       { uk:'Швидкі відповіді', en:'Quick replies' },
  'ch.q1':          { uk:'Підтверджую запис ✅', en:'Confirming lesson ✅' },
  'ch.q2':          { uk:'Запис скасовано ❌',   en:'Lesson cancelled ❌' },
  'ch.q3':          { uk:'Нагадую: завтра',      en:'Reminder: tomorrow' },
  'ch.q4':          { uk:'Будь ласка, підтвердіть', en:'Please confirm' },
  'ch.q5':          { uk:'До зустрічі 👋',        en:'See you 👋'         },

  // STATS
  'st2.week':        { uk:'Тиждень',    en:'Week'       },
  'st2.month':       { uk:'Місяць',     en:'Month'      },
  'st2.year':        { uk:'Рік',        en:'Year'       },
  'st2.dynamics':    { uk:'Динаміка',   en:'Dynamics'   },
  'st2.split':       { uk:'Розподіл',   en:'Split'      },
  'st2.by_day':      { uk:'По днях',    en:'By day'     },
  'st2.top5':        { uk:'Топ-5 клієнтів', en:'Top-5 clients' },
  'st2.export':      { uk:'Експорт',    en:'Export'     },
  'st2.avg_check':   { uk:'Серед. чек', en:'Avg. check' },
  'st2.per_period':  { uk:'за період',  en:'per period' },
  'st2.per_lesson':  { uk:'дохід / запис', en:'per lesson' },

  // SERVICES
  'sv.title':        { uk:'Послуги',     en:'Services'   },
  'sv.active':       { uk:'Активних послуг', en:'Active services' },
  'sv.total_lessons':{ uk:'Записів всього', en:'Total lessons' },
  'sv.drag_hint':    { uk:'тягни ☰ для зміни порядку', en:'drag ☰ to reorder' },
  'sv.add':          { uk:'Додати нову послугу', en:'Add new service' },
  'sv.edit_title':   { uk:'Редагування послуги', en:'Edit service' },
  'sv.new_title':    { uk:'Нова послуга', en:'New service' },
  'sv.duration':     { uk:'Тривалість',  en:'Duration'   },
  'sv.price':        { uk:'Ціна',        en:'Price'      },
  'sv.color':        { uk:'Колір слоту', en:'Slot color' },
  'sv.description':  { uk:'Опис',        en:'Description'},
  'sv.access':       { uk:'Доступ (категорії)', en:'Access (categories)' },
  'sv.delete_confirm':{ uk:'Видалити послугу?', en:'Delete service?' },
  'sv.archive':      { uk:'Архівувати',  en:'Archive'    },
  'sv.delete_forever':{ uk:'Видалити назавжди', en:'Delete forever' },
  'sv.preview':      { uk:'Попередній перегляд слоту', en:'Slot preview' },

  // TEMPLATES
  'tpl.title':       { uk:'Шаблони',     en:'Templates'  },
  'tpl.auto':        { uk:'Авто ⚡',     en:'Auto ⚡'    },
  'tpl.manual':      { uk:'Ручні ✋',    en:'Manual ✋'  },
  'tpl.active':      { uk:'Активних',    en:'Active'     },
  'tpl.send':        { uk:'Надіслати',   en:'Send'       },
  'tpl.new':         { uk:'Новий шаблон', en:'New template' },
  'tpl.edit_title':  { uk:'Редагування шаблону', en:'Edit template' },
  'tpl.name':        { uk:'Назва шаблону', en:'Template name' },
  'tpl.category':    { uk:'Категорія',   en:'Category'   },
  'tpl.channel':     { uk:'Канал',       en:'Channel'    },
  'tpl.trigger':     { uk:'Умова відправки', en:'Trigger' },
  'tpl.body':        { uk:'Текст повідомлення', en:'Message text' },
  'tpl.vars':        { uk:'Змінні — клікни щоб вставити:', en:'Variables — click to insert:' },
  'tpl.preview':     { uk:'Попередній перегляд', en:'Preview' },
  'tpl.to_whom':     { uk:'Кому надіслати', en:'Send to'  },
  'tpl.all_students':{ uk:'Всі клієнти',    en:'All clients' },
  'tpl.edit_before': { uk:'Редагувати перед відправкою', en:'Edit before sending' },
  'tpl.not_found':   { uk:'Шаблонів не знайдено', en:'No templates found' },
  'tpl.create':      { uk:'Створити',    en:'Create'     },

  // SETTINGS SECTIONS
  'set.schedule.title':   { uk:'Робочий графік',       en:'Work Schedule'       },
  'set.schedule.info_t':  { uk:'Робочий час',           en:'Working hours'       },
  'set.schedule.info':    { uk:"Тут ви налаштовуєте, коли ви працюєте. Клієнти бачать у додатку тільки ті години, які ви відкрили.\n\n• Початок дня і Кінець дня — з котрої і до котрої години ви приймаєте клієнтів. Поза цими межами записатись не можна.\n• Днів у розкладі — на скільки днів уперед одразу видно календар. Наприклад, 14 — це два тижні.\n• Блокувати минулі записи — коли увімкнено, вже проведені записи не вдасться випадково змінити, перенести чи скасувати. Вони стають блідішими.\n• Кнопка підказок «?» — показує або ховає круглу кнопку з довідкою над розкладом.\n\nНижче — тижневий графік. Для кожного дня тижня можна зробити вихідний, поставити свій робочий час (наприклад, у суботу коротший день) і додати обідню перерву. У перерву клієнти записатись не можуть, а у вашому розкладі вона видна смугою «Обід».", en:"Here you set when you work. Clients only see the hours you have opened.\n\n• Day start and Day end — the hours between which you take clients. Nobody can book outside them.\n• Days in schedule — how many days ahead the calendar shows at once. For example, 14 is two weeks.\n• Lock past bookings — when on, lessons that already happened cannot be changed, moved or cancelled by accident. They look paler.\n• Hints button «?» — shows or hides the round help button above the schedule.\n\nBelow is the weekly plan. For every weekday you can set a day off, your own working hours (for example a shorter Saturday) and a lunch break. Clients cannot book during the break, and it appears as a «Lunch» stripe in your schedule." },
  'set.schedule.start':   { uk:'Початок дня',           en:'Day start'           },
  'set.schedule.end':     { uk:'Кінець дня',            en:'Day end'             },
  'set.schedule.days':    { uk:'Днів у розкладі',       en:'Days shown'          },
  'set.schedule.hint_s':  { uk:'Перший доступний слот', en:'First available slot'},
  'set.schedule.hint_e':  { uk:'Останній слот',         en:'Last slot'           },
  'set.schedule.weekends':{ uk:'Вихідні дні',           en:'Weekends'            },
  'set.days':             { uk:'Пн,Вт,Ср,Чт,Пт,Сб,Нд', en:'Mo,Tu,We,Th,Fr,Sa,Su'},

  'set.lunch.title':  { uk:'Обідня перерва',  en:'Lunch break'    },
  'set.lunch.info_t': { uk:'Обідня перерва',  en:'Lunch break'    },
  'set.lunch.info':   { uk:'Заблокований часовий проміжок посередині дня. Клієнти не зможуть записатись на цей час. У розкладі він відображається смугою «Обід».', en:'A blocked time slot in the middle of the day. Clients cannot book during this time. It appears as a "Lunch" bar in the schedule.' },
  'set.lunch.enable': { uk:'Увімкнути перерву', en:'Enable break'  },
  'set.lunch.from':   { uk:'З',               en:'From'           },
  'set.lunch.to':     { uk:'До',              en:'To'             },

  'set.snap.title':   { uk:'Крок часу',        en:'Time grid step' },
  'set.snap.info_t':  { uk:'Точність часу',    en:'Snap step'      },
  'set.snap.info':    { uk:"Тут ви обираєте, наскільки «дрібно» рухається час у розкладі.\n\n• Крок при перетягуванні — коли ви пересуваєте запис пальцем, час сам «прилипає» до сітки. 15 хв — зручно для більшості, 5 хв — точніше, 30 і 60 хв — швидше, але грубіше. Наприклад, при кроці 30 хв запис стане на 10:00 або 10:30, а не на 10:12.\n• Крок слота (довгий тап) — якщо довго потримати палець на порожньому місці в розкладі, створиться новий слот. Цей крок каже, з яких хвилин він може починатися (при 30 хв — 9:00, 9:30, 10:00…).\n• Час у слоті — показувати або ховати написи «з–до» всередині слотів у розкладі.\n• Автокольори клієнтів — увімкнено: система сама розфарбовує слоти клієнтів різними кольорами. Вимкнено: колір ви вибираєте вручну в картці клієнта.", en:"Here you choose how «fine» the time moves in the schedule.\n\n• Drag step — when you move a booking with your finger, the time snaps to the grid. 15 min suits most people, 5 min is more precise, 30 and 60 min are faster but coarser. For example, with a 30 min step a booking lands on 10:00 or 10:30, not 10:12.\n• Slot step (long tap) — if you hold your finger on an empty spot in the schedule, a new slot is created. This step says which minutes it can start on (at 30 min — 9:00, 9:30, 10:00…).\n• Time in slot — show or hide the «from–to» labels inside slots.\n• Auto client colours — on: the system colours clients' slots automatically. Off: you pick the colour by hand in the client card." },
  'set.snap.label':   { uk:'Крок при перетягуванні', en:'Drag snap step' },

  'set.svc.title':    { uk:'Послуги та ціни', en:'Services & prices' },
  'set.svc.info_t':   { uk:'Послуги',         en:'Services'       },
  'set.svc.info':     { uk:'Кожна послуга — це тип запису з тривалістю і ціною. Колір відображається прямо в слоті розкладу. Вимкнена послуга не доступна клієнтам для запису.', en:'Each service is a lesson type with duration and price. The color appears directly in the schedule slot. A disabled service is unavailable for booking.' },
  'set.svc.duration_lbl': { uk:'Час (хв)',    en:'Time (min)'     },
  'set.svc.price_lbl':    { uk:'Ціна (₴)',    en:'Price (₴)'      },
  'set.svc.color':    { uk:'Колір слоту',      en:'Slot color'     },
  'set.svc.add':      { uk:'+ Додати послугу', en:'+ Add service'  },
  'set.svc.del':      { uk:'× Видалити послугу', en:'× Delete service' },

  'set.cat.title':    { uk:'Категорії клієнтів', en:'Client categories' },
  'set.cat.info_t':   { uk:'Для чого категорії?', en:'What are categories?' },
  'set.cat.info':     { uk:'Розділяють клієнтів за типом доступу. VIP бачить ексклюзивні послуги та слоти, Стандарт — базові. Категорія відображається на картці клієнта і у розкладі. Можна додати власну з будь-яким кольором.', en:'They group clients by access level. VIP sees exclusive services and slots, Standard — basic ones. The category appears on the client card and in the schedule.' },
  'set.cat.color':    { uk:'Колір',            en:'Color'          },
  'set.cat.add':      { uk:'+ Додати категорію', en:'+ Add category' },
  'set.cat.new':      { uk:'Нова категорія',   en:'New category'   },

  'set.restr.title':  { uk:'Обмеження для клієнтів', en:'Client restrictions' },
  'set.restr.info_t': { uk:'Контроль записів',    en:'Booking control'     },
  'set.restr.info':   { uk:"Тут ви вирішуєте, що клієнт може робити сам, без вашої участі, і як далеко вперед він бачить розклад.\n\n• Клієнт може переносити запис / скасовувати — два окремі дозволи. Вимкнули — клієнтові доведеться писати або дзвонити вам.\n• Заборона запису — за скільки годин до запису клієнт уже не може записатись або змінити запис. Наприклад, 2 год: на запис о 15:00 після 13:00 він самостійно вже не запишеться. 0 — без обмеження.\n• Горизонт генерації слотів — на скільки днів уперед кнопка в розкладі (зелена, з квадратиками) розставляє вільні слоти. Наприклад, 30 — на місяць.\n• Календар наперед (приватні) і (автошкола) — на скільки днів уперед клієнт бачить вільні слоти у своєму додатку. Для приватних клієнтів і для автошколи можна задати по-різному.\n• Мінімальний інтервал між записами — скільки днів має пройти між двома записами однієї людини. 0 — без обмеження, 1 — не частіше ніж раз на день. Захищає розклад від надто частих записів однієї людини.", en:"Here you decide what a client can do on their own, without you, and how far ahead they see the schedule.\n\n• Client can reschedule / cancel — two separate permissions. Turned off — the client has to write or call you.\n• Booking cut-off — how many hours before a lesson the client can no longer book or change a booking. For example, 2 h: for a 15:00 lesson they cannot book on their own after 13:00. 0 — no limit.\n• Slot generation horizon — how many days ahead the button in the schedule (green, with squares) lays out free slots. For example, 30 is a month.\n• Calendar ahead (private) and (driving school) — how many days ahead the client sees free slots in their app. It can differ for private clients and driving-school clients.\n• Minimum interval between bookings — how many days must pass between two bookings of the same person. 0 — no limit, 1 — not more than once a day. It protects the schedule from one person booking too often." },
  'set.restr.reschedule': { uk:'Клієнт може переносити запис', en:'Client can reschedule' },
  'set.restr.cancel':     { uk:'Клієнт може скасовувати',       en:'Client can cancel'     },
  'set.restr.cutoff':     { uk:'Заборона запису',               en:'Booking cut-off'        },
  'set.restr.cutoff_h':   { uk:'Годин до запису',                en:'Hours before lesson'    },
  'set.restr.slotGen':    { uk:'Горизонт генерації слотів',      en:'Slot generation horizon' },
  'set.restr.slotGen_h':  { uk:'На скільки днів вперед ця кнопка у розкладі розставляє вільні слоти', en:'How many days ahead this button in the schedule auto-fills free slots' },
  'set.restr.calendar':   { uk:'Календар наперед (індивідуальні)',   en:'Calendar ahead (individual)' },
  'set.restr.calendar_h': { uk:'Днів видно клієнтові з індивідуальним записом',  en:'Days visible to an individual-booking client' },
  'set.restr.schoolCalendar':   { uk:'Календар наперед (стандарт)', en:'Calendar ahead (standard)' },
  'set.restr.schoolCalendar_h': { uk:'Днів видно клієнтові зі стандартним записом',  en:'Days visible to standard client' },
  'set.pkg':            { uk:'Годин у пакеті', en:'Hours in package' },
  'set.pkg_h':          { uk:'Скільки годин проходить клієнт зі «Стандартом», перш ніж йому відкриваються індивідуальні записи. 0 — без пакета, обмежень немає.', en:'How many hours a Standard client completes before individual bookings unlock. 0 — no package, no limit.' },

  'set.queue.title':  { uk:'Черга', en:'Queue' },
  'set.queue.info_t': { uk:'Черга', en:'Queue' },
  'set.queue.info':   { uk:"Черга потрібна, коли клієнт хоче записатись на вже зайнятий час. Він стає в чергу сам у своєму додатку, а коли місце звільняється, система пропонує його тим, хто чекає.\n\n• Вимагати підтвердження — увімкнено: нові записи не підтверджуються самі, а мають статус «Очікує», поки ви їх не підтвердите. Вимкнено: запис одразу вважається підтвердженим.\n\nРежим черги — хто отримає звільнене місце:\n• Автоматично — місце отримує той, хто став у чергу першим. Йому одразу приходить пропозиція; якщо він не відповів, система пропонує наступному.\n• Розсилка — пропозиція приходить усім у черзі одночасно. Місце отримує той, хто підтвердить першим.\n• Вручну — система нічого не пропонує сама. Ви дивитесь список очікуючих на вкладці «Черга» і самі обираєте, кого запросити.", en:"A queue is needed when a client wants a time that is already taken. They join the queue themselves in their app, and when the place frees up the system offers it to those waiting.\n\n• Require confirmation — on: new bookings are not confirmed automatically but stay «Pending» until you confirm them. Off: a booking is confirmed at once.\n\nQueue mode — who gets the freed place:\n• Automatic — the place goes to whoever joined the queue first. They get an offer at once; if they do not answer, the system offers it to the next one.\n• Broadcast — the offer goes to everyone in the queue at the same time. The place goes to whoever confirms first.\n• Manual — the system offers nothing by itself. You look at the waiting list on the «Queue» tab and choose whom to invite." },
  'set.queue.require':{ uk:'Вимагати підтвердження',        en:'Require confirmation'   },
  'set.queue.require_h':{ uk:'Нові записи отримують статус «Очікує»', en:'New bookings get "Pending" status' },
  'set.queue.mode':   { uk:'Режим черги',                    en:'Queue mode'             },
  'set.queue.fifo':   { uk:'Автоматично',                    en:'FIFO'                   },
  'set.queue.fifo_h': { uk:'Перший хто записався — отримує місце автоматично', en:'First registered gets the spot automatically' },
  'set.queue.bc':     { uk:'Розсилка',                       en:'Broadcast'              },
  'set.queue.bc_h':   { uk:'Розсилка всім — хто перший підтвердить, той записаний', en:'Sent to all — first to confirm gets booked' },
  'set.queue.manual': { uk:'Вручну',                          en:'Manual'                 },
  'set.queue.manual_h':{ uk:'Майстер сам обирає кого запросити', en:'Master chooses who to invite' },

  'set.sticky.title': { uk:'Вільні слоти поряд із записом', en:'Free slots near booking' },
  'set.sticky.info_t':{ uk:'Як це працює', en:'How it works' },
  'set.sticky.info':  { uk:"Це «склеювання» розкладу, щоб між уроками не залишалось незручних вільних «дірок».\n\nУвімкнено — клієнт бачить лише ті вільні години, що стоять впритул до іншого запису або до обідньої перерви. Поодинокі вільні години «посеред» вільного часу ховаються.\n\nПриклад: у вас є запис з 12:00 до 14:00.\n• «Тільки перед записом» — клієнт зможе обрати 11:00 (годину до запису).\n• «Тільки після запису» — зможе обрати 14:00 (годину після).\n• «Обидва» — обидві можливості.\nОбід працює так само: можна записатись впритул до обіду або одразу після нього.\n\nПерший вільний слот дня показується завжди. Вимкнено — клієнт бачить усі вільні слоти без обмежень.", en:"This «glues» the schedule together so no awkward free gaps are left between lessons.\n\nOn — the client only sees free hours that are right next to another booking or the lunch break. Lone free hours in the middle of free time are hidden.\n\nExample: you have a booking from 12:00 to 14:00.\n• «Before a booking only» — the client can pick 11:00 (the hour before).\n• «After a booking only» — they can pick 14:00 (the hour after).\n• «Both» — both options.\nLunch works the same way: a client can book right before lunch or right after it.\n\nThe first free slot of the day is always shown. Off — the client sees all free slots without limits." },
  'set.sticky.before':{ uk:'Тільки перед записом',      en:'Only before booking'    },
  'set.sticky.after': { uk:'Тільки після запису',       en:'Only after booking'     },
  'set.sticky.both':  { uk:'Обидва — клієнт обирає сам', en:'Both — client chooses' },

  'set.auto.title':   { uk:'Авто-повідомлення',     en:'Auto messages'          },
  'set.auto.info_t':  { uk:'Автоматичні повідомлення', en:'Automatic messages'   },
  'set.auto.info':    { uk:'Повідомлення, які система надсилає клієнтам автоматично, без твоєї участі. Тексти самих повідомлень редагуються у вкладці «Шаблони». «Нагадування» — можна додати кілька, кожне надсилається за вказану кількість годин до запису (наприклад, за 24 і за 2 години) — зменшує кількість пропущених записів. «Автоматичне скасування» — якщо клієнт не підтвердив запис, система сама скасовує його. «Автозапит з черги» — коли звільняється слот, система сама пропонує його наступному в черзі, без ручного втручання майстра.', en:'Messages the system sends to clients automatically, without your involvement. Edit the message text itself in the Templates tab. "Reminder" — you can add several, each sent a set number of hours before the lesson (e.g. 24h and 2h before) — reduces missed lessons. "Auto-cancel" — if a client doesn\'t confirm a booking, the system cancels it automatically. "Auto queue offer" — when a slot frees up, the system automatically offers it to the next client in the queue, with no manual action from the master.' },
  'set.auto.reminder':{ uk:'Нагадування',            en:'Reminder'               },
  'set.auto.rem_h':   { uk:'год до запису',            en:'hr before lesson'       },
  'set.auto.welcome': { uk:'Вітання новому клієнтові',   en:'Welcome new client'    },
  'set.auto.confirm': { uk:'Підтвердження запису',    en:'Booking confirmation'   },
  'set.auto.cancel':  { uk:'Повідомлення про скасування', en:'Cancellation notice'},
  'set.auto.queue':   { uk:'Пропозиція з черги',      en:'Queue offer'            },

  'set.nav.title':    { uk:'Нижня навігація',  en:'Bottom navigation'  },
  'set.nav.info_t':   { uk:'Вкладки меню',     en:'Menu tabs'          },
  'set.nav.info':     { uk:'Вибери які вкладки показувати в нижній панелі. Вимкнені вкладки зникають з меню але залишаються доступними. «Налаштування» завжди активні.', en:'Choose which tabs to show in the bottom bar. Disabled tabs disappear from the menu but remain accessible. "Settings" is always visible.' },

  'set.look.title':   { uk:'Зовнішній вигляд', en:'Appearance'         },
  'set.look.info_t':  { uk:'Тема і мова',       en:'Theme and language' },
  'set.look.info':    { uk:'Темна тема зручна для роботи вночі або в слабоосвітленому місці. Мова впливає на текст у системних повідомленнях і кнопках клієнтського додатку.', en:'Dark theme is great for working at night or in low light. Language affects text in system messages and buttons in the client app.' },
  'set.look.theme':   { uk:'Тема',              en:'Theme'              },
  'set.look.dark':    { uk:'Темна',             en:'Dark'               },
  'set.look.light':   { uk:'Світла',            en:'Light'              },
  'set.look.lang':    { uk:'Мова',              en:'Language'           },
};

export const createT = lang => key => {
  const entry = S[key];
  if (!entry) return key;
  return entry[lang] || entry.uk || key;
};

// Global language (for components that don't receive lang prop)
export let globalLang = localStorage.getItem('id4lang') || 'uk';
export const setGlobalLang = l => { globalLang = l; localStorage.setItem('id4lang', l); };
export const T = key => createT(globalLang)(key);
